### ISSUE TITLE
Security Manager Bug

### ISSUE THREAD

**Issue by Blackneeed** [SzymekkYT/RadianceOS#20]
Whenever i open the Security Manager application on RadianceOS the entire taskbar all windows crash and only the desktop wallpaper is left on the screen

https://github.com/SzymekkYT/RadianceOS/assets/121721929/d68be4b2-01cc-459e-9c90-c54bd185db7e

**Comment by MrBisquit** [comment]
Hello! I'm the person working on the Security for RadianceOS.
I see that it crashes when the Security Manager app is started, this is caused by the UAC (User Access Control) window pops up, this stops everything else from rendering while it asks the user the question. Unfortunately, it appears that the branch you are on lacks the actual UAC UI and is just left with the buggy mess that was before. This should be fixed on the dev branch, though it still does not fully work and none of the buttons will work, I'm still working on this and will get back to you once it it fixed. :)

**Comment by Blackneeed** [comment]
Thank you very much, but does the security manager itself need UAC admin to run? Cause that is a bit strange

**Comment by MrBisquit** [comment]
> Thank you very much, but does the security manager itself need UAC admin to run? Cause that is a bit strange

Yes, it requires elevation so that it can do things at a higher level than a User level application.

Also, if you download the latest version from the dev branch and build it, the UAC UI actually works now (Partially). There are still quite a few bugs but I'll get them sorted out pretty soon.

**Comment by MrBisquit** [comment]
Issue should be resolved on the dev branch @Blackneeed.
